name: llamaindex_agent
services:
  vector_db:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage 
    networks:
      - internal_net
  app:
    depends_on:
      - vector_db
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 8000:8000
    secrets:
      - openai_key
      - tavily_key
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

secrets:
  openai_key:
    environment: openai_api_key
  tavily_key:
    environment: tavily_api_key